/**
 * Generated Metadata Rendering Module
 * Handles display of AI-generated metadata
 */

import { state, $ } from '../state.js';
import { countGeneratedFields } from '../utils/component.js';
import { renderMetadataDetails } from './metadata.js';
import { renderDevHandoff } from './report.js';

/**
 * Update generated metadata display
 * @param {Object} gen - Generated metadata object
 */
export function updateGenerated(gen) {
  console.log('═══════════════════════════════════════════════════════════════════');
  console.log('[UI] ✨ METADATA GENERATED BY CLAUDE');
  console.log('═══════════════════════════════════════════════════════════════════');

  if (gen) {
    // Log each generated field - safely handle different types
    if (gen.description) {
      const desc = String(gen.description);
      console.log('[UI] ✅ Generated Description:', desc.substring(0, 100) + (desc.length > 100 ? '...' : ''));
    }
    if (gen.tags) {
      const tags = Array.isArray(gen.tags) ? gen.tags.join(', ') : String(gen.tags);
      console.log('[UI] ✅ Generated Tags:', tags);
    }
    if (gen.notes) {
      const notes = String(gen.notes);
      console.log('[UI] ✅ Generated Notes:', notes.substring(0, 80) + (notes.length > 80 ? '...' : ''));
    }
    if (gen.category) {
      console.log('[UI] ✅ Generated Category:', gen.category);
    }
    if (gen.level) {
      console.log('[UI] ✅ Generated Atomic Level:', gen.level);
    }
    if (gen.ariaLabel) {
      console.log('[UI] ✅ Generated ARIA Label:', gen.ariaLabel);
    }
    if (gen.a11y) {
      const a11y = Array.isArray(gen.a11y) ? gen.a11y.join(', ') : String(gen.a11y);
      console.log('[UI] ✅ Generated A11y Guidelines:', a11y);
    }

    // Log variant descriptions
    const variantDescs = gen.variantDescriptions || gen.variants || {};
    if (variantDescs && typeof variantDescs === 'object') {
      const variantCount = Object.keys(variantDescs).length;
      if (variantCount > 0) {
        console.log('[UI] ✅ Generated Variant Descriptions:', variantCount);
        Object.entries(variantDescs).forEach(([name, desc]) => {
          console.log(`    - ${name}: ${String(desc).substring(0, 60)}...`);
        });
      }
    }

    // Log property descriptions
    const propDescs = gen.propertyDescriptions || {};
    if (propDescs && typeof propDescs === 'object') {
      const propCount = Object.keys(propDescs).length;
      if (propCount > 0) {
        console.log('[UI] ✅ Generated Property Descriptions:', propCount);
        Object.entries(propDescs).forEach(([name, desc]) => {
          console.log(`    - ${name}: ${String(desc).substring(0, 60)}...`);
        });
      } else {
        console.log('[UI] ⚠️ No property descriptions in generated metadata');
      }
    }

    // Log formatted description length
    if (gen.formattedDescription || gen.formattedForFigma) {
      const formatted = String(gen.formattedDescription || gen.formattedForFigma);
      console.log('[UI] 📄 Formatted Output Length:', formatted.length, 'chars');
    }

    // Log tokens - CRITICAL for Dev Info tab
    if (gen.tokens) {
      if (Array.isArray(gen.tokens)) {
        console.log('[UI] ✅ Generated Tokens (array):', gen.tokens.length, 'items');
        console.log('[UI]    First token:', JSON.stringify(gen.tokens[0]));
      } else if (typeof gen.tokens === 'object') {
        console.log('[UI] ✅ Generated Tokens (object):', Object.keys(gen.tokens).join(', '));
      }
    } else {
      console.log('[UI] ⚠️ No tokens in generated metadata');
    }
  } else {
    console.log('[UI] ⚠️ No generated metadata received');
  }
  console.log('───────────────────────────────────────────────────────────────────');

  // Check if metadata is already complete (all required fields present in Figma)
  // Must check BOTH basic fields AND accessibility fields
  const meta = state.metadata;
  const csl = meta?.componentSetLevel || { present: [] };
  const a11yMeta = meta?.accessibilityMetadata || {};

  // Basic required fields
  const requiredFieldKeys = ['description', 'tags', 'notes', 'category', 'level'];
  const allBasicPresent = requiredFieldKeys.every(f => csl.present.includes(f));

  // Accessibility fields - check if they exist in Figma OR if we have generated values
  const hasA11yInFigma = a11yMeta.hasAriaLabel && a11yMeta.hasA11yNotes &&
                        a11yMeta.hasFocusStates && a11yMeta.hasContrastInfo;

  // Only consider "all required present" if BOTH basic AND a11y are complete in Figma
  const allRequiredPresent = allBasicPresent && hasA11yInFigma;

  if (allRequiredPresent) {
    console.log('[UI] ℹ️ All required fields already present in Figma - showing as existing, not generated');

    // IMPORTANT: Still store generated data for Dev Info tab (property descriptions, etc.)
    // These are reference data for developers, not "metadata to apply"
    state.generated = gen;

    // Check if there are property/variant descriptions to apply
    const hasPropertyDescs = gen?.propertyDescriptions && Object.keys(gen.propertyDescriptions).length > 0;
    const hasVariantDescs = gen?.variantDescriptions && Object.keys(gen.variantDescriptions).length > 0;
    const hasNewDataToApply = hasPropertyDescs || hasVariantDescs;

    const applyBtn = $('applyMetaBtn');
    const applyBtnMeta = $('applyMetaBtnMeta');

    if (hasNewDataToApply) {
      // Show Apply buttons - there are property/variant descriptions to inject
      console.log('[UI] 📋 Property/variant descriptions available to apply');
      if (applyBtn) applyBtn.style.display = 'flex';
      if (applyBtnMeta) applyBtnMeta.style.display = 'flex';

      // Update status to show metadata complete + optional enhancements available
      const metadataStatusEl = $('metadataStatus');
      if (metadataStatusEl) {
        const propCount = hasPropertyDescs ? Object.keys(gen.propertyDescriptions).length : 0;
        const variantCount = hasVariantDescs ? Object.keys(gen.variantDescriptions).length : 0;
        // Clearer message: main metadata is complete, optional property/variant descriptions available
        const descText = `${propCount > 0 ? propCount + ' prop' : ''}${propCount > 0 && variantCount > 0 ? ', ' : ''}${variantCount > 0 ? variantCount + ' variant' : ''} desc. available`;
        metadataStatusEl.innerHTML = `<div style="text-align: center; font-size: 13px; color: #fff;">✓ Metadata complete</div><div style="text-align: center; font-size: 12px; color: rgba(255,255,255,0.85); margin-top: 2px;">${descText}</div>`;
        metadataStatusEl.className = 'score-status ready';
        metadataStatusEl.style.background = 'var(--success)';
        metadataStatusEl.style.padding = '8px 12px';
        metadataStatusEl.style.borderRadius = '6px';
      }
    } else {
      // Hide Apply buttons since there's nothing new to apply
      if (applyBtn) applyBtn.style.display = 'none';
      if (applyBtnMeta) applyBtnMeta.style.display = 'none';

      // Update status to show metadata is complete
      const metadataStatusEl = $('metadataStatus');
      if (metadataStatusEl) {
        metadataStatusEl.textContent = '✓ Metadata complete - all fields exist in Figma';
        metadataStatusEl.className = 'score-status ready';
      }
    }

    // Re-render the Metadata tab to show generated property/variant descriptions
    if (state.metadata) {
      const metadataDetailsEl = $('metadataDetails');
      if (metadataDetailsEl) {
        metadataDetailsEl.innerHTML = renderMetadataDetails(state.metadata, gen);
        document.querySelectorAll('.metadata-section-header').forEach(header => {
          header.onclick = () => header.parentElement.classList.toggle('collapsed');
        });
      }
    }

    // Still render Dev Info tab with generated property/variant descriptions
    renderDevHandoff();
    return;
  }

  // FIX: Even if basic fields are present, we still need to store and display
  // generated accessibility data if a11y fields are missing
  if (allBasicPresent && !hasA11yInFigma) {
    console.log('[UI] ℹ️ Basic fields present, but accessibility fields need generation');
  }

  // Store generated data in state (only if fields are missing)
  state.generated = gen;

  // Update the Review tab's generated metadata preview
  if (gen?.formattedDescription || gen?.formattedForFigma) {
    const generatedMetaEl = $('generatedMeta');
    if (generatedMetaEl) {
      generatedMetaEl.textContent = gen.formattedDescription || gen.formattedForFigma;
    }
  }

  // Re-render the Metadata tab with generated values
  if (state.metadata) {
    const metadataDetailsEl = $('metadataDetails');
    if (metadataDetailsEl) {
      metadataDetailsEl.innerHTML = renderMetadataDetails(state.metadata, gen);
      // Re-attach event listeners for collapsible sections
      document.querySelectorAll('.metadata-section-header').forEach(header => {
        header.onclick = () => header.parentElement.classList.toggle('collapsed');
      });
    }
  }

  // Update metadata score status to show generated
  // Pass state.metadata to only count fields that are truly NEW (not already in Figma)
  const genCount = countGeneratedFields(gen, state.metadata);
  if (genCount > 0) {
    console.log('[UI] 📊 Total Fields Generated:', genCount);
    const metadataStatusEl = $('metadataStatus');
    if (metadataStatusEl) {
      metadataStatusEl.textContent = `✨ ${genCount} field(s) generated - Ready to apply!`;
      metadataStatusEl.className = 'score-status ready';
    }
    // Show the Apply button in Metadata tab
    const applyMetaBtnMetaEl = $('applyMetaBtnMeta');
    if (applyMetaBtnMetaEl) {
      applyMetaBtnMetaEl.style.display = 'flex';
    }
    // Also show in Review tab (if it exists)
    const applyMetaBtnEl = $('applyMetaBtn');
    if (applyMetaBtnEl) {
      applyMetaBtnEl.style.display = 'flex';
    }
  }

  // Always render Dev Info tab with the latest generated data
  renderDevHandoff();
}
