/**
 * @file aid-pairing.ts
 * @description AID Plugin Pairing System
 *
 * This module handles secure pairing between the Figma plugin and the AID system.
 * Uses a one-time password (OTP) code generated by Claude Code for authentication.
 *
 * Flow:
 * 1. User runs `/aid-pair` in Claude Code -> generates 6-digit OTP
 * 2. User enters OTP in Figma plugin within 5 minutes
 * 3. Plugin sends OTP to server for validation
 * 4. Server returns JWT token for ongoing communication
 *
 * @security
 *   - OTP codes are single-use and expire after 5 minutes
 *   - Rate limiting: max 3 attempts per IP per minute
 *   - JWT tokens expire after 24 hours (configurable)
 */

import crypto from 'crypto';
import { generateToken } from './jwt-middleware.js';

interface PairingCode {
  code: string;
  tenantId: string;
  projectPath: string;
  createdAt: number;
  expiresAt: number;
  used: boolean;
  attempts: number;
}

interface PairingResult {
  success: boolean;
  token?: string;
  tenantId?: string;
  projectPath?: string;
  error?: string;
  attemptsRemaining?: number;
}

// In-memory storage for pairing codes (use Redis in production)
let pairingCodes = new Map<string, PairingCode>();
let rateLimiter = new Map<string, { count: number; resetAt: number }>();

/**
 * Clear all pairing codes and rate limits (for testing only)
 */
export function clearPairingState(): void {
  pairingCodes = new Map();
  rateLimiter = new Map();
}

// Configuration
const OTP_LENGTH = 6;
const OTP_EXPIRY_MS = 5 * 60 * 1000; // 5 minutes
const MAX_ATTEMPTS = 3;
const RATE_LIMIT_WINDOW_MS = 60 * 1000; // 1 minute
const MAX_REQUESTS_PER_WINDOW = 5;

/**
 * Generate a new OTP code for AID pairing
 * Called from Claude Code via /aid-pair command
 */
export function generatePairingCode(tenantId: string, projectPath: string): string {
  // Generate cryptographically secure 6-digit code
  const code = crypto.randomInt(100000, 999999).toString();

  // Store the code
  const now = Date.now();
  pairingCodes.set(code, {
    code,
    tenantId,
    projectPath,
    createdAt: now,
    expiresAt: now + OTP_EXPIRY_MS,
    used: false,
    attempts: 0
  });

  // Clean up expired codes
  cleanupExpiredCodes();

  return code;
}

/**
 * Validate an OTP code from the Figma plugin
 * Returns JWT token on success
 */
export function validatePairingCode(code: string, clientIp: string): PairingResult {
  // Rate limiting
  if (!checkRateLimit(clientIp)) {
    return {
      success: false,
      error: 'Too many attempts. Please wait 1 minute before trying again.'
    };
  }

  // Look up the code
  const pairing = pairingCodes.get(code);

  if (!pairing) {
    return {
      success: false,
      error: 'Invalid pairing code. Please generate a new code with /aid-pair.'
    };
  }

  // Check if expired
  if (Date.now() > pairing.expiresAt) {
    pairingCodes.delete(code);
    return {
      success: false,
      error: 'Pairing code expired. Please generate a new code with /aid-pair.'
    };
  }

  // Check if already used
  if (pairing.used) {
    return {
      success: false,
      error: 'This pairing code has already been used. Generate a new one with /aid-pair.'
    };
  }

  // Check attempts
  pairing.attempts++;
  if (pairing.attempts > MAX_ATTEMPTS) {
    pairingCodes.delete(code);
    return {
      success: false,
      error: 'Maximum attempts exceeded. Please generate a new code with /aid-pair.'
    };
  }

  // Success! Mark as used and generate JWT
  pairing.used = true;

  const token = generateToken({
    sub: `figma-plugin-${pairing.tenantId}`,
    tenantId: pairing.tenantId,
    roles: ['figma-plugin']
  });

  // Clean up
  pairingCodes.delete(code);

  return {
    success: true,
    token,
    tenantId: pairing.tenantId,
    projectPath: pairing.projectPath
  };
}

/**
 * Check pairing status (for polling from plugin)
 */
export function getPairingStatus(code: string): {
  valid: boolean;
  expired: boolean;
  used: boolean;
  remainingSeconds: number;
} {
  const pairing = pairingCodes.get(code);

  if (!pairing) {
    return { valid: false, expired: true, used: false, remainingSeconds: 0 };
  }

  const now = Date.now();
  const remainingMs = Math.max(0, pairing.expiresAt - now);

  return {
    valid: !pairing.used && now < pairing.expiresAt,
    expired: now >= pairing.expiresAt,
    used: pairing.used,
    remainingSeconds: Math.floor(remainingMs / 1000)
  };
}

/**
 * Rate limit check
 */
function checkRateLimit(clientIp: string): boolean {
  const now = Date.now();
  const entry = rateLimiter.get(clientIp);

  if (!entry || now > entry.resetAt) {
    rateLimiter.set(clientIp, {
      count: 1,
      resetAt: now + RATE_LIMIT_WINDOW_MS
    });
    return true;
  }

  if (entry.count >= MAX_REQUESTS_PER_WINDOW) {
    return false;
  }

  entry.count++;
  return true;
}

/**
 * Clean up expired pairing codes
 */
function cleanupExpiredCodes(): void {
  const now = Date.now();
  for (const [code, pairing] of pairingCodes.entries()) {
    if (now > pairing.expiresAt) {
      pairingCodes.delete(code);
    }
  }
}

/**
 * Get formatted message for displaying the OTP
 */
export function formatPairingCodeMessage(code: string, locale: 'en' | 'he' = 'en'): string {
  const messages = {
    en: `
╔══════════════════════════════════════════════════════════╗
║                  🔗 AID PAIRING CODE                      ║
╠══════════════════════════════════════════════════════════╣
║                                                          ║
║        Enter this code in your Figma plugin:             ║
║                                                          ║
║                    ${code.slice(0, 3)} ${code.slice(3)}                      ║
║                                                          ║
║        ⏱️  Valid for 5 minutes                           ║
║        🔒 Single use only                                ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝

In Figma:
1. Open the Atomic Design Extractor plugin
2. Go to Settings tab
3. Click "Connect to AID"
4. Enter the code above
`,
    he: `
╔══════════════════════════════════════════════════════════╗
║                  🔗 קוד התחברות AID                       ║
╠══════════════════════════════════════════════════════════╣
║                                                          ║
║        הכנס קוד זה בתוסף ה-Figma שלך:                     ║
║                                                          ║
║                    ${code.slice(0, 3)} ${code.slice(3)}                      ║
║                                                          ║
║        ⏱️  תקף ל-5 דקות                                  ║
║        🔒 שימוש חד פעמי בלבד                             ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝

ב-Figma:
1. פתח את התוסף Atomic Design Extractor
2. עבור ללשונית הגדרות
3. לחץ "התחבר ל-AID"
4. הכנס את הקוד למעלה
`
  };

  return messages[locale];
}

/**
 * Revoke all pairing codes for a tenant
 * Used when logging out or resetting
 */
export function revokeTenantCodes(tenantId: string): number {
  let count = 0;
  for (const [code, pairing] of pairingCodes.entries()) {
    if (pairing.tenantId === tenantId) {
      pairingCodes.delete(code);
      count++;
    }
  }
  return count;
}
